cmd/guardian/main.go, gqt/gqt_suite_test.go
This requires a submodule update for ducati to get the `New()` method.
Pulling this wil bring in libnetwork via ducati's vendor directory.
Acceptance tests now use go 1.5's vendoring experiment.
=> Use ducati constructor

cmd/guardian/main.go, gqt/gqt_suite_test.go
Reverts cloudfoundry-incubator/guardian#13.
I tried making `vendor` and `Gosub` work, but it turns out it is not very simple. I fixed the compilation issues for nested tests (GATS and GQT) but not the BOSH release. 
We are using the script `scripts/sync-package-specs` that generates the `guardian` BOSH package specs. Unfortunately, this relies heavily on `gosub`. Gosub is misinterpreting the `ducati/vendor/` directory contents (`libnetwork` currently) as gosub dependencies. This leads to an undeployable BOSH release.
We need to think about this and either adopt a different approach for the Ducati dependency management, or fix Gosub (which might be simpler). But unfortunately, I have to revert this PR to fix the CI :(
=> Revert "Use ducati constructor"

cmd/guardian/main.go, gqt/gqt_suite_test.go
Hey there.
Here's an attempt at implementing the external client behavior we discussed on Tuesday. 
Highlights:
- [Ducati](https://github.com/cloudfoundry-incubator/ducati) has turned into a standalone binary, which accepts a rudimentary form of RPC via JSON on `stdin`/`stdout`.  It also has its [own BOSH release](https://github.com/cloudfoundry-incubator/ducati-release).
- Guardian no longer depends on Ducati.  Instead...
- Guardian now interacts with Ducati via a new [Guardian External Networker (GEN) Client](https://github.com/cloudfoundry-incubator/genclient).  This is a work-in-progress, thin Go client for an
external networker.
- The Guardian command line flag to use this stuff changes to `networkModulePath`
- default value is empty string, means use Kawasaki
- otherwise the string …
=> Replace direct reference to ducati with new GEN Client

cmd/guardian/main.go, cmd/kawasaki/main.go, kawasaki/config_creator.go, kawasaki/config_creator_test.go, kawasaki/dns/resolv_file_compiler.go, kawasaki/dns/resolv_file_compiler_test.go, kawasaki/networker.go, kawasaki/networker_test.go, pkg/vars/vars.go, pkg/vars/vars_test.go
This implements a `-dnsServer` command line option (that may be given multiple times) which will force the container to use those DNS servers rather than guessing from the host's `resolv.conf`.
See also cloudfoundry-incubator/garden-linux#60.
This will have matching PRs in `garden` and `guardian-release`, followed by a second PR in the garden family to implement the same.
=> Support using custom DNS servers instead of picking from the host

kawasaki/configurer_test.go, kawasaki/devices/bridge_linux.go, kawasaki/devices/devices_suite_test.go, kawasaki/netns/netns_execer_linux_test.go, kawasaki/netns/netns_suite_test.go
- `lsof` will warn if user is not root; ignore `stderr`
- devices + netns suites will fail if not root; ignore those suites in that case
- `go vet` wants keys for all fields (netlink.Bridge)
=> Make tests (vet/ginko) pass on Linux (outside of concourse)

gqt/net_test.go
Our AWS seems to be flakier than yours.  This helps, a lot.
cc @rosenhouse
=> GQT net test before-each retries on DNS lookups

rundmc/starter.go, rundmc/starter_test.go
* parse the expected header, bail if it's not what we expect
* fix skipping the second line of /proc/cgroups; this meant we were
skipping a subsytem this whole time
* handle subsystems being disabled by skipping them
* handle subsystems that are enabled but not mounted anywhere by
mounting them on their own
=> more conservatively process /proc/cgroups

gardener/container.go, gardener/gardener.go, gardener/gardener_test.go
This should satisfy https://www.pivotaltracker.com/story/show/116986065.
Haven't added a GQT yet as I'm not sure there's a great way to test this kind of thing without introducing either flakiness or slowness (plus the actual logic for that lives in `garden` anyway).
=> persist and report container grace time

guardiancmd/command.go
previously Garden would always introduce additional cgroups mount points
even if /sys/fs/cgroup was already set up. this makes things look a bit
more sane as /sys/fs/cgroup is the conventional location.
=> set up cgroups in /sys/fs/cgroup if tag not specified

gardener/fakes/fake_networker.go, gardener/gardener.go, gardener/gardener_test.go, gqt/net_test.go, kawasaki/composite_networker.go, kawasaki/composite_networker_test.go, kawasaki/fakes/fake_network_hooker.go, kawasaki/fakes/fake_networker.go, kawasaki/networker.go, kawasaki/networker_test.go, netplugin/plugin.go, netplugin/plugin_test.go
`ContainerSpec` properties which begin with the string `network.` are provided to the external network plugin.
It is actually kind of flexible: since the `Networker.Hooks()` takes a `ContainerSpec`, it has some freedom to change what sort of data it passes to the hooks, and how.
- @rosenhouse & @sykesm
=> Propagate network properties to network plugins

rundmc/starter.go, rundmc/starter_test.go
this fixes detection of already-mounted cgroups in the case where there
are symlinks under `/sys/fs/cgroup`, e.g.:
drwxr-xr-x 2 root root  0 Apr 25 16:50 blkio
lrwxrwxrwx 1 root root 11 Apr 25 16:47 cpu -> cpu,cpuacct
drwxr-xr-x 2 root root  0 Apr 25 16:50 cpu,cpuacct
lrwxrwxrwx 1 root root 11 Apr 25 16:47 cpuacct -> cpu,cpuacct
drwxr-xr-x 2 root root  0 Apr 25 16:50 cpuset
drwxr-xr-x 2 root root  0 Apr 25 16:50 devices
drwxr-xr-x 2 root root  0 Apr 25 16:50 freezer
drwxr-xr-x 2 root root  0 Apr 25 16:50 hugetlb
drwxr-xr-x 2 root root  0 Apr 25 16:50 memory
lrwxrwxrwx 1 root root 16 Apr 25 16:47 net_cls -> net_cls,net_prio
drwxr-xr-x 2 root root  0 Apr 25 16:50 net_cls,net_prio
lrwxrwxrwx 1 root root 16 Apr 25 16:47 net_prio -> net_cls,net_prio
drwxr-xr-x 2 root root  0 Apr 25 16:50 …
=> force 'mountpoint' to follow symlinks

netplugin/external_networker.go, netplugin/external_networker_test.go
Similar to [#127923587](https://www.pivotaltracker.com/story/show/117043597) except the logs come on stderr now, since stdout is reserved for returning container properties.
=> Capture and log external networker's stderr

rundmc/nstar/nstar.c
Hi!
I am working on porting Cloud Foundry projects to Power microprocessor architecture.
For the ppc64 architecture execveat syscall has different code. I suggest to use __PPC64__ macro to check and set the right value.
Similar PR was merged for garden-linux project - https://github.com/cloudfoundry/garden-linux/pull/64
=> Add support for execveat syscall in case of ppc64 arch

gqt/gqt_suite_test.go, gqt/graph_test.go, gqt/rootfs_test.go, gqt/runner/runner.go, rundmc/dadoo/execrunner_linux_test.go
Note: we were not able to run unit-tests. We got errors even when running a totally clean version of garden-runc. So we are submitting the PR but this needs to be tested before getting pulling in.
``` 
mkdir /var/run/netns failed: Permission denied
Cannot remove namespace file "/var/run/netns/my-netns-1": No such file or directory
• Failure in Spec Setup (BeforeEach) [0.022 seconds]
Container [BeforeEach] when the container interface does not exist returns the error
/home/pivotal/workspace/garden-runc-release/src/code.cloudfoundry.org/guardian/kawasaki/configure/container_linux_test.go:148
No future change is possible.  Bailing out early after 0.010s.
 Expected
     <int>: 1
 to match exit code:
     <int>: 0
 /home/pivotal/workspace/garden-runc-release/src/code.cloudfoundry.org/guardian/k …
```
=> Make rootfs and tarbin parameters to be passed in to guardian ifrit runner

gardener/gardener.go, gardener/gardener_test.go, gqt/cmd/fake_grootfs/main.go, gqt/gqt_suite_test.go, gqt/rootfs_test.go, gqt/runner/runner.go, guardiancmd/command.go, volplugin/composite_volume_creator.go, volplugin/composite_volume_creator_test.go, volplugin/grootfs.go, volplugin/grootfs_test.go, volplugin/volplugin_suite_test.go
Enable garden to use grootfs to create rootfs filesystems, when the path begins with `grootfs+`.
e.g.
```
grootfs+docker:///ubuntu
```
* Adds the grootfs volume creator, that should shell out to the `--oci-image-bin`. 
* Replace the `VolumeCreator` used in the `Gardener` with a `CompositeVolumeCreator`.
* `CompositeVolumeCreator` implements the VolumeCreator interface and is aware of the GrootFS VC and the GardenShed VC. It then decides with volume creator to use for each operation, based on the rootfs url scheme.
* `CompositeVolumeCreator` also adds a new property to the container `volumePlugin` which may be `grootfs` or `garden-shed`.
* The garbage collection had to be moved from the `Gardener` to inside the `CompositeVolumeCreator` since it has no information about which container is …
=> Grootfs volume creator

gqt/create_test.go, gqt/net_test.go, guardiancmd/command.go, kawasaki/networker.go, netplugin/external_networker.go, netplugin/external_networker_test.go
- `Network` sets ExternalIP property and configures DNS resolv conf
- `NetIn` allocates ports from port pool and persists them to the container's MappedPorts
- `NetOut` persists rules to a well-named container property, so that external components may discover the full set of rules
[Story #127325611](https://www.pivotaltracker.com/story/show/127325611)
cc @rosenhouse
=> Enhacements to support external networkers

gqt/cmd/fake_image_plugin/main.go, gqt/rootfs_test.go, imageplugin/external_image_manager.go, imageplugin/external_image_manager_test.go, imageplugin/imageplugin_suite_test.go
The image plugin should call the image binary with the bundle path instead of the rootfs path when deleting.
Signed-off-by: Tiago Scolari tscolari@pivotal.io
Signed-off-by: I am groot.
=> Use bundle path instead of rootfs for img-plugin deletion

gardener/container.go, gardener/gardener.go, gardener/gardener_test.go, gardener/gardenerfakes/fake_volume_creator.go, gardener/noop_volume_creator.go, gardener/noop_volume_creator_test.go, imageplugin/external_image_manager.go, imageplugin/external_image_manager_test.go
Adds ImagePlugin `Metrics` implementation.
* The `VolumeCreator` interface had to be updated to contain the rootfs path.
[#133928963]
Part of https://www.pivotaltracker.com/story/show/133928963
Signed-off-by: Claudia Beresford <cberesford@pivotal.io>
=> Implement image plugin `Metrics` command

gqt/cmd/fake_image_plugin/main.go, gqt/rootfs_test.go, imageplugin/external_image_manager.go, imageplugin/external_image_manager_test.go, imageplugin/image.go
This enables loading environmental variables from the `image.json` when creating images based on a docker image using the `imageplugin`.
https://www.pivotaltracker.com/story/show/133744595
=> Add imageplugin support to env variables

gqt/net_test.go, netplugin/external_networker.go, netplugin/external_networker_test.go
Guardian forwards BulkNetOut calls on to the external networker instead of making several NetOut calls.
cc @genevievelesperance
=> BulkNetOut calls bulk-net-out on external networker

imageplugin/external_image_manager.go, imageplugin/external_image_manager_test.go
* Imageplugin logs will be relogged (namespaced) in the garden logger.
* Error messages will include the image plugin stdout instead of the
stderr (stderr is for logs only).
* Add 2 new GO dependencies.
[finishes #133833213]
Signed-off-by: Claudia Beresford <cberesford@pivotal.io>
=> Relog imageplugin logs into the garden logger

imageplugin/external_image_manager.go, imageplugin/external_image_manager_test.go
* `docker:///ubuntu#14.04` should be forwarded as `docker:///ubuntu:14.04`
[#134343139] -> https://www.pivotaltracker.com/story/show/134343139
Signed-off-by: Claudia Beresford <cberesford@pivotal.io>
=> Fix image tag parsing when using external image plugin

guardiancmd/command.go
This allows guardian (and external-image-plugins) to use a default rootfs that's not a directory (e.g. tar file)
[#136770727](https://www.pivotaltracker.com/story/show/136770727)
=> Relax default container rootfs flag directory restriction

guardiancmd/command.go, guardiancmd/command_linux.go, guardiancmd/command_windows.go, rundmc/runrunc/create.go
These changes enable creating and destroying containers with [`winc`](https://github.com/cloudfoundry-incubator/winc) used as the runtime plugin.
* Close logfile after reading
* Do not write files in /etc on windows
=> Allow winc.exe to be used as the runtime_plugin

gqt/cmd/fake_runtime_plugin/main.go, gqt/runtime_plugin_test.go
This should backfill the runtime plugin tests to ensure that stdout and stderr are properly retrieved from the runtime plugin.
(Let me know if you want to move the `Context` or `It` block to another place or change the descriptions)
=> backfile runtime plugin stdout, stderr tests

rundmc/runrunc/exec_preparer.go, rundmc/runrunc/exec_test.go
required for Windows to respect the desired user to run a process as: https://github.com/opencontainers/runtime-spec/blob/master/config.md#example-windows-2
=> pass username to process spec.json

gqt/bind_mount_test.go, guardiancmd/command.go, rundmc/goci/bundle.go, rundmc/goci/bundle_test.go
This allows for nested mounts within a bind mount, which is needed for
the bosh-warden-cpi to properly attach "persistent" disks.
This PR replaces #92 as it solves the problem more directly without new configuration. The current default is `rprivate` which breaks nested mounts within bind mounts, garden-linux used to do `private` so this puts that behaviour back in place.
Closes #92
=> Change default rootfs propagation to 'private'

gardener/gardener.go, gardener/gardener_test.go, rundmc/bundlerules/windows.go, rundmc/bundlerules/windows_test.go, rundmc/goci/bundle.go, rundmc/goci/bundle_test.go
- Read LayerFolders from image plugin
- Guardian writes windows.LayerFolders for bundle
[#149185707]
Signed-off-by: Amin Jamali <ajamali@pivotal.io>
=> Pass Windows LayerFolders from image plugin to runtime plugin

guardiancmd/command_linux.go
Otherwise pty devices will be failed to create on some Linux distros.
How to reproduce:
Create a SLES 11 SP4 container, then
$ python -c "import pty; pty.fork()"
...
OSError: out of pty devices
Reference: https://lwn.net/Articles/688809/
> SUS requires that the group ID of the slave device should not be that
> of the creating process, but rather some definite, though unspecified,
> value. The GNU C Library (glibc) takes responsibility for implementing
> this requirement; it quite reasonably chooses the ID of the group named
> "tty" (often 5) to fill this role. If the devpts filesystem is mounted
> with options gid=5,mode=620, this group ID and the required access mode
> will be used and glibc will be happy. If not, glibc will (if so
> configured) run a setuid helper found at …
=> Mount devpts with option `gid=5`

gqt/cmd/fake_runtime_plugin/main.go, gqt/runner/runner.go, gqt/runtime_plugin_test.go, guardiancmd/command.go, rundmc/runrunc/create.go, rundmc/runrunc/create_test.go, rundmc/runrunc/runrunc.go
This is used by `winc` in place of the removed `--runc-root` flag.
We did not pass the extra args to any other subcommands of the runtime-plugin (i.e. `exec`) because it wasn't necessary for our use case.
=> Allow extra args to be passed to runtime plugin create

gqt/runtime_plugin_test.go, rundmc/execrunner/execrunner_windows.go, rundmc/execrunner/execrunner_windows_test.go
Retrieve `winc exec` logs in `garden-windows` job when running with `log_level: debug`
Signed-off-by: Mark DeLillo <mdelillo@pivotal.io>
=> Forward logs from windows execrunner to guardian

gqt/runtime_plugin_test.go, guardiancmd/command_windows.go, rundmc/execrunner/windows_execrunner.go, rundmc/execrunner/windows_execrunner_test.go, rundmc/goci/bundle.go, rundmc/peas/pea_creator.go, rundmc/peas/pea_creator_test.go
This PR allows the DirectExecRunner (used on Windows) to be called with either `exec` or `run`.
It satisfies the peas API but doesn't have full parity with linux. For example, memory limits are not inherited from the parent container (i.e. [these tests](https://github.com/cloudfoundry/garden-integration-tests/blob/f14395737215a599f9d647c51e2db1cd137533e2/peas_test.go#L185-L216) won't pass on Windows).
@mdelillo @aminjam
=> Add support for peas on Windows

netplugin/external_networker.go, netplugin/external_networker_test.go
The container networking external networking plugin is going to start outputting warnings to stderr even when exit code is zero. We would want this to be seen even when the log level is not debug.
/cc @ameowlia
=> Log external networker plugin Stderr when stderr is not empty

guardiancmd/command.go
When building guardian on 32bit platforms go will complain for overflows because strconv.Itoa's argument is of type int.
Switch to FormatInt that accepts a int64.
=> Fix int overflow in 32bit builds

guardiancmd/command.go
not sure why this was being set, but it doesn't seem like a 'sane default' for folks using `gdn` for projects concerned with security
=> gdn: don't force --allow-host-access

go.mod, go.sum
Hi,
Full disclosure: I didn't run the tests as described under `garden-runc-release` - the only thing I tried was running `gdn` from an armv7l `concourse`, which fixed the issue I described in #124.
Also, this PR has the results of a `go mod tidy` (thus, not leaving the old shasum in `go.sum`, but replacing with the one for the new version). 
Please let me know if there's anything else I'd need to do or if there's a special reason why this dep wasn't bumped.
Thanks!
---
fixes #124
Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>
=> Bump idmapper dep

go.mod, go.sum, vendor/modules.txt
Although we may not be vulnerable to all of these CVEs because the dependencies particular codepaths may not be used, this PR guarantees they won't be:
- CVE-2014-0048
- BDSA-2017-1196
- CVE-2019-5736
- CVE-2014-9356
- CVE-2014-5277
- BDSA-2016-1133
- CVE-2014-0047
- CVE-2019-16884
- CVE-2014-6407
- BDSA-2019-1633
- CVE-2015-3627
- CVE-2021-21284
- CVE-2014-9358
=> Force safe version of docker/docker and runc

rundmc/nstar/nstar.c
--no-same-permissions and --no-same-owner are default for non root
users. When running nstar as root tar fails to set permissions on an
extracted file because the user in rootfs can not see files created by
the original user. Set these flags explicitly so that they get applied
for "root" user as well.
=> Extract files as provided user

gardener/gardener.go, gardener/gardener_test.go
In case if fail to create container (e.g. external networker is down) and we fail to immediately destroy it in the defer clause, we want to be able to find that container later and try to destroy it. So if later external networker comes up we can clean up containers and not leak them. 
To achieve that, we modified the Containers() call to be able to take in the `garden.state` property. It used to be always set to `created` which only returned successfully created containers. When Rep tried to get containers for clean up it was not getting containers that were partially created because they didn't have the `created` state. So now we can pass in the value `all` which will indicate to garden that we want containers in all states. When `all` is passed in we remove `garden.state` from the …
=> Containers that are partially created can be fetched for cleanup

gardener/container_network_metrics_provider_linux.go, gardener/container_network_metrics_provider_linux_test.go, guardiancmd/command_linux.go
* [The current approach of fetching container network metrics](https://github.com/cloudfoundry/guardian/blob/8789f016ea2d285889aa47947092b5665b24605c/gardener/container_network_metrics_provider_linux.go#L40-L49) fails for docker images without a shell.
* This change fetches the container network metrics by simply utilizing the container's network namespace.
* https://github.com/cloudfoundry/guardian/issues/422
=> use netns to fetch container network metrics

go.mod
This is a follow up to:
- https://github.com/cloudfoundry/guardian/commit/4ce98fefbc9834cfcb6517cc92b1320aae4c8b8e
Prevents the following bug:
```
$ go get -t -u ./... && go mod tidy && go mod vendor && go vet ./...
vendor/go.opentelemetry.io/otel/internal/global/trace.go:56:30: cannot use &tracerProvider{} (value of type *tracerProvider) as trace.TracerProvider value in variable declaration: *tracerProvider does not implement trace.TracerProvider (missing method tracerProvider)
vendor/go.opentelemetry.io/otel/internal/global/trace.go:104:10: cannot use val (variable of type *tracer) as trace.Tracer value in return statement: *tracer does not implement trace.Tracer (missing method tracer)
vendor/go.opentelemetry.io/otel/internal/global/trace.go:109:9: cannot use t (variable of type …
```
=> Pin otel/trace to v1.15.1

go.mod
Context: https://ci.funtime.lol/teams/wg-arp-garden/pipelines/garden-runc-release/jobs/bump-dependencies-go-mod/builds/2
=> Fix failing update for guardian

guardiancmd/cleanup.go, guardiancmd/command.go, guardiancmd/command_linux.go, guardiancmd/server.go, metrics/metrics_provider.go, metrics/metrics_provider_test.go, rundmc/runcontainerd/nerd/nerd.go
When container processes get stuck blocked in kernel code (e.g. a connection disappears mid-write to an NFS volume store), the processes are unkillable even with `kill -9`.
This change adds the following:
- updated log messages when kill -9 has failed, indicating that the VM running garden must be rebooted.
- a new `UnkillableContainers` metric is emitted that can be used to determine if a VM has any containers that garden was unable to kill.
=> Provide better visibility into containers that cannot be killed

guardiancmd/command_windows.go
Context: https://github.com/cloudfoundry/guardian/pull/429/files
=> Fix windows version for guardiancmd

netplugin/external_networker.go
The error message captures both the error and the action that led to the error. Because the most common action that causes this error is the 'down' action (meaning, network teardown), a common error message was 'external networker down,' leading many people to beleive that the entire vxlan-policy-agent was no longer running.
The new error message tries to make clear that 'down' is the action, to avoid this misunderstanding
=> Improve external networker error message

guardiancmd/command.go, guardiancmd/server.go
Summary
To use with https://github.com/cloudfoundry/garden/pull/118
=> Add ReadHeaderTimeout server option

go.mod, go.sum, vendor/modules.txt
Summary
Fix `go get -u ./...`.
Updating dependencies is failing because our containerd is pinned so its dependencies need to be pinned as well.
=> Pin go.opentelemetry.io/contrib/instrumentation for containerd

rundmc/goci/serialize_test.go
Summary
Fixes test assertion to match new error message returned in go 1.23.
Breaking Change? no
=> Fix test for golang 1.23

rundmc/nstar/nstar.c
Summary
Execveat has code 281 on ARM64. For nstar to work on ARM64 we need to define it conditionally.
=> Define execveat code for arm64 in nstar

gqt/cmd/fake_image_plugin/main.go, gqt/cmd/fake_runtime_plugin/main.go, gqt/containerdrunner/runner.go, gqt/runner/runner.go, rundmc/cgroups/starter_linux.go, rundmc/runcontainerd/cgroup_manager.go
This reverts commit 27f29b64ba1e008d43df40ab56e7f1ac6789598d.
Summary
Looks like cgroup folder changes break Inigo tests
=> Revert "Fix file/dir creation permissions"

gardener/gardener.go, gardener/volume_provider.go, guardiancmd/command.go, guardiancmd/kernel_min_version_checker.go, kawasaki/configure/container.go, kawasaki/networker.go, rundmc/bundlerules/limits.go, rundmc/bundlerules/mount_options_linux.go, rundmc/bundlerules/windows.go, rundmc/containerizer.go, rundmc/execrunner/dadoo/winsize.go, rundmc/preparerootfs/prepare_linux.go, rundmc/processes/builder.go, rundmc/runcontainerd/runcontainerd.go, vendor/code.cloudfoundry.org/garden/container.go, vendor/code.cloudfoundry.org/idmapper/idmapping.go
Summary
Many ignores to avoid changing public interfaces and work through issues caused by libcontainer using int, but garden + linux using uint32 for things.
Updated a few things for better types to avoid casting, or casting in the opposite direction for more safety
Breaking Change?
=> Address integer overflows across guardian

rundmc/execrunner/dadoo/winsize.go
Summary
We want these as uint16, but needed to update garden as well.
Breaking Change? no
=> Convert back to uint16 for window sizes

rundmc/runrunc/stats.go, vendor/code.cloudfoundry.org/garden/container.go
Summary
Logic: file + anon + swap - inactive_file
this is similar to cgroups v1 but uses the correct field from runc events
Context: https://github.com/opencontainers/runc/pull/3933
Fixes: cloudfoundry/diego-release#995
=> In cgroups v2 we need to use different fields for memory

guardiancmd/lager_flag.go
Summary
Cleanup logging time stamp property
=> cleanup time format property

guardiancmd/lager_flag.go
Summary
fix static checks on lager
`root@fc353076ebb3:/repo/scripts/docker# ./test.bash guardian
Setting up controllers for cgroup v2
Verifying: verify_go repo/src/guardian
go version go1.24.4 linux/amd64
Verifying: verify_go_version_match_bosh_release repo
Verifying: verify_gofmt repo/src/guardian
Verifying: verify_govet repo/src/guardian
Verifying: verify_staticcheck repo/src/guardian
`
=> fix static checks on lager

gqt/create_linux_test.go, gqt/rebalancing_test.go
Summary
Fixing few cgroups v2 related test cases
1. `  [FAILED] Timed out after 5.000s.
Expected
<int64>: 875
to equal
<int64>: 825
In [It] at: /tmp/build/a587a358/repo/src/guardian/vendor/github.com/onsi/gomega/internal/async_assertion.go:145 @ 07/21/25 22:26:55.796
Full Stack Trace
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000325500, {0x19c11c8, 0xc00e5f22f0}, {0x0, 0x0, 0x0})
/tmp/build/a587a358/repo/src/guardian/vendor/github.com/onsi/gomega/internal/async_assertion.go:145 +0xc5
code.cloudfoundry.org/guardian/gqt_test.init.func29.5.2.2()
/tmp/build/a587a358/repo/src/guardian/gqt/rebalancing_test.go:104 +0x205`
=> containters shares conversion test between cgroups v1/v2

gardener/container.go, gardener/gardener.go, gqt/net_plugin_test.go, kawasaki/config_creator.go, kawasaki/dns/hosts_file_compiler.go, kawasaki/dns/hosts_file_compiler_test.go, kawasaki/kawasakifakes/fake_host_file_compiler.go, kawasaki/resolv.go, kawasaki/resolv_test.go, netplugin/external_networker.go, netplugin/external_networker_test.go, vendor/code.cloudfoundry.org/garden/container.go
Summary
[RFC0038](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0038-ipv6-dual-stack-for-cf.md)
[Tracking Issue](https://github.com/cloudfoundry/community/issues/1107)
Add IPv6 support to /etc/hosts compilation
Example hosts file after the change, when IPv6 is enabled:
```shell
vcap@a2df59ce-163d-478a-4799-902f:~$ cat /etc/hosts
127.0.0.1 localhost
::1 localhost
10.147.240.5 a2df59ce-163d-478a-4799-902f
2600:1f18:75b9:1c1e:2::5 a2df59ce-163d-478a-4799-902f
```
=> [RFC0038] Support IPv6 in hosts file compilation
